import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { Book, fetchBookAsync } from '../../../api/books'
import { BookForm } from '../../../components/BookForm/BookForm'

const NewBookPage: NextPage = () => {
  const router = useRouter()
  const { pid } = router.query

  const [book, setBook] = useState<Book | null>(null)

  const loadBook = async (id: any) => {
    const response = await fetchBookAsync(id)
    if (response) {
      setBook(response)
    }
  }

  useEffect(() => {
    if (pid) {
      loadBook(pid)
    }
  }, [pid])

  return (
    <>
      <Head>
        <title>Edit book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {book && <BookForm book={book} />}
      </div>
    </>
  )
}

export default NewBookPage
