import { useState } from 'react'
import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { Alert, Button, Form, Input } from 'antd'
import { signInAsync } from '../../store/slices/user'
import { useAppDispatch } from '../../store/hooks'

const SignInPage: NextPage = () => {
  const dispatch = useAppDispatch()

  const [error, setError] = useState<string>('')

  const onFinish = async (values: any) => {
    setError('')
    const response: any = await dispatch(signInAsync({
      email: values.email,
      password: values.password,
    }))
    if (response?.payload?.error?.message) {
      setError(response.payload.error.message)
    }
  }

  const onFinishFailed = (errorInfo: any) => {
    console.log('Failed:', errorInfo)
  }

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Sign In</h1>

      {error && <Alert message={error} type="error" />}

      <br />

      <Form
        name="basic"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
        initialValues={{ remember: true }}
        onFinish={onFinish}
        onFinishFailed={onFinishFailed}
        autoComplete="off"
      >
        <Form.Item
          label="Email"
          name="email"
          rules={[{ required: true, type: 'email', message: 'Please input your username!' }]}
        >
          <Input />
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          rules={[{ required: true, message: 'Please input your password!' }]}
        >
          <Input.Password />
        </Form.Item>

        <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
          <span> or </span>
          <Link href={'/auth/signup'}>Creane new account</Link>
        </Form.Item>
      </Form>
    </div>
  )
}

export default SignInPage
