import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'

const Profile: NextPage = () => {
  const router = useRouter()
  const { pid } = router.query

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Profile: {pid}
      </div>
    </>
  )
}

export default Profile
