import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'antd'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        <Button type="primary">Primary Button</Button>
      </p>
      <p>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </p>
    </div>
  )
}

export default Home
