import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { List } from 'antd'
import { Book, fetchBooksAsync } from '../../api/books'

const BooksPage: NextPage = () => {
  const [books, setBooks] = useState<Book[]>([])

  const loadBooks = async () => {
    const list = await fetchBooksAsync()
    if (list?.data) {
      setBooks(list.data)
    }
  }

  useEffect(() => {
    loadBooks()
  }, [])

  return (
    <>
      <Head>
        <title>Books list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Books list</h1>

        <List
          bordered
          itemLayout="horizontal"
          dataSource={books}
          renderItem={item => (
            <List.Item>
              <List.Item.Meta
                title={<Link href={`/books/${item.id}`}>{item.title}</Link>}
                description={item.description}
              />
            </List.Item>
          )}
        />
      <p>
        <Link href={`/books/new`}>Add new book</Link>
      </p>
      </div>
    </>
  )
}

export default BooksPage
