import type { NextPage } from 'next'
import Head from 'next/head'
import { BookForm } from '../../components/BookForm/BookForm'

const NewBookPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Add new book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <BookForm />
      </div>
    </>
  )
}

export default NewBookPage
